### ISSUE TITLE
It would be great the opcion to add 2 subtitles

### ISSUE THREAD

**Issue by oribe522** [manzing/widevine-L3-WEB-DL-Script#1]
Your script its great! It would be so nice that we can add 2 .srt subtitles FR and EN. It will really help, please. You may think its useless, but here in LATAM we build MKV dual audio and dual srt al the time. Thanks

**Comment by manzing** [comment]
Added in todo list if possible.

**Comment by oribe522** [comment]
> Added in todo list if possible.

THnaks, really THANKS!!!!!

**Comment by manzing** [comment]
Feature is added. Please see https://github.com/manzing/widevine-L3-WEB-DL-Script/discussions/3 to get more information about use of external subtitles.

**Comment by oribe522** [comment]
> Feature is added. Please see #3 to get more information about use of external subtitles.

Thanks, Thanks too much for your time, work and dedication to others.
